import{useMemo,useState}from"react";
import{ArrowRight,Bone,Cat,Check,ChevronDown,Clock3,Dog,HeartPulse,MapPin,Menu,MessageCircle,PackageCheck,PawPrint,Phone,Pill,Search,ShieldCheck,ShoppingBag,Sparkles,Tag,Truck,X}from"lucide-react";
const B={name:"Mercadão Pet Capão Redondo",wa:"551123684371",waDisplay:"(11) 2368-4371",phone:"(11) 2368-4371",phoneLink:"tel:+551123684371",address:"Av. Ellis Maas, 641 - Capão Redondo, São Paulo - SP, 05859-000",maps:"https://www.google.com/maps/search/?api=1&query=Av.%20Ellis%20Maas%20641%20Cap%C3%A3o%20Redondo%20S%C3%A3o%20Paulo%20SP%2005859-000"};
const products=[
{id:1,cat:"Rações",icon:Dog,name:"Ração Premium para cães",detail:"Pacote demonstrativo de 15 kg",price:159.90,old:179.90,badge:"Oferta exemplo"},
{id:2,cat:"Rações",icon:Cat,name:"Ração para gatos castrados",detail:"Pacote demonstrativo de 10 kg",price:139.90},
{id:3,cat:"Farmácia",icon:Pill,name:"Antipulgas para cães",detail:"Produto demonstrativo, consulte orientação",price:49.90},
{id:4,cat:"Farmácia",icon:HeartPulse,name:"Suplemento vitamínico pet",detail:"Frasco demonstrativo",price:39.90},
{id:5,cat:"Higiene",icon:Sparkles,name:"Shampoo neutro pet",detail:"Frasco demonstrativo de 500 ml",price:29.90},
{id:6,cat:"Higiene",icon:PackageCheck,name:"Tapete higiênico",detail:"Pacote demonstrativo com 30 unidades",price:54.90},
{id:7,cat:"Acessórios",icon:PawPrint,name:"Coleira ajustável",detail:"Tamanhos P, M e G",price:34.90},
{id:8,cat:"Acessórios",icon:ShoppingBag,name:"Cama pet confortável",detail:"Tamanho médio",price:109.90},
{id:9,cat:"Petiscos",icon:Bone,name:"Petisco crocante",detail:"Embalagem demonstrativa de 500 g",price:22.90},
{id:10,cat:"Brinquedos",icon:Dog,name:"Mordedor resistente",detail:"Modelo demonstrativo",price:27.90},
{id:11,cat:"Acessórios",icon:Cat,name:"Arranhador compacto",detail:"Modelo demonstrativo",price:89.90},
{id:12,cat:"Farmácia",icon:ShieldCheck,name:"Higiene bucal pet",detail:"Kit demonstrativo",price:44.90}
];
const benefits=[[Truck,"Entrega","Consulte bairros e condições."],[PawPrint,"Leva e traz","Disponibilidade sujeita à confirmação."],[ShoppingBag,"Grande variedade","Produtos para cães, gatos e outros pets."],[Tag,"Promoções","Ofertas e descontos para clientes."]];
const money=v=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function App(){const[menu,setMenu]=useState(false);const[cat,setCat]=useState("Todos");const[search,setSearch]=useState("");const[form,setForm]=useState({name:"",phone:"",pet:"Cachorro",need:"Comprar produtos",message:""});const valid=useMemo(()=>form.name.trim().length>=3&&form.phone.replace(/\D/g,"").length>=10,[form]);const cats=["Todos",...new Set(products.map(p=>p.cat))];const filtered=products.filter(p=>(cat==="Todos"||p.cat===cat)&&p.name.toLowerCase().includes(search.toLowerCase()));const nav=[["inicio","Início"],["catalogo","Catálogo"],["beneficios","Benefícios"],["farmacia","Farmácia Pet"],["contato","Contato"]];function go(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenu(false)}function wa(msg="Olá! Gostaria de informações sobre produtos e serviços do Mercadão Pet Capão Redondo."){window.open(`https://wa.me/${B.wa}?text=${encodeURIComponent(msg)}`,"_blank","noopener,noreferrer")}function order(p){wa(`Olá! Gostaria de confirmar disponibilidade e preço real de: ${p.name}. Valor demonstrativo exibido: ${money(p.price)}.`)}function submit(e){e.preventDefault();if(!valid)return;wa(`Olá! Meu nome é ${form.name}. Telefone: ${form.phone}. Pet: ${form.pet}. Interesse: ${form.need}. ${form.message||"Gostaria de receber informações."}`)}return <main className="min-h-screen bg-[#f8fbf5] text-[#113b2f]">
<div className="bg-[#ffd54f] px-4 py-2 text-center text-xs font-black">PROJETO DEMONSTRATIVO: produtos, preços, promoções e disponibilidade são exemplos e precisam ser confirmados pela empresa.</div>
<header className="sticky top-0 z-50 border-b border-green-100 bg-white/95 backdrop-blur"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><button onClick={()=>go("inicio")} className="flex items-center gap-3 text-left"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#147d64] text-white"><PawPrint size={28}/></span><span><strong className="block text-xl">Mercadão Pet</strong><span className="text-[10px] font-black uppercase tracking-[.2em] text-slate-500">Capão Redondo</span></span></button><nav className="hidden gap-7 lg:flex">{nav.map(([id,l])=><button key={id} onClick={()=>go(id)} className="text-sm font-bold text-slate-600 hover:text-[#147d64]">{l}</button>)}</nav><button onClick={()=>wa()} className="hidden items-center gap-2 rounded-xl bg-[#25a866] px-5 py-3 font-black text-white md:flex"><MessageCircle size={18}/>WhatsApp</button><button onClick={()=>setMenu(!menu)} className="lg:hidden">{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="border-t bg-white p-5 lg:hidden">{nav.map(([id,l])=><button key={id} onClick={()=>go(id)} className="block w-full rounded-xl px-4 py-3 text-left font-bold hover:bg-green-50">{l}</button>)}</div>}</header>
<section id="inicio" className="relative bg-[#113b2f] text-white"><div className="absolute inset-0 opacity-35" style={{backgroundImage:"radial-gradient(circle at 85% 15%,#147d64 0,transparent 32%),radial-gradient(circle at 10% 90%,#ffd54f 0,transparent 25%)"}}/><div className="relative mx-auto grid min-h-[700px] max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-bold text-[#ffd54f]"><ShieldCheck size={18}/>Tudo para o seu pet</span><h1 className="mt-7 text-5xl font-black leading-[1.02] sm:text-6xl lg:text-7xl">Variedade, cuidado e economia para quem faz parte da família.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-green-100">Rações, acessórios, brinquedos, higiene e farmácia pet com atendimento no Capão Redondo.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={()=>go("catalogo")} className="flex items-center justify-center gap-2 rounded-xl bg-[#ffd54f] px-7 py-4 font-black text-[#113b2f]">Ver catálogo<ShoppingBag size={19}/></button><button onClick={()=>wa()} className="flex items-center justify-center gap-2 rounded-xl border border-white/25 px-7 py-4 font-black">Pedir no WhatsApp<MessageCircle size={19}/></button></div><div className="mt-10 flex flex-wrap gap-5 text-sm text-green-100">{["Entrega", "Leva e traz", "Estacionamento grátis"].map(t=><span key={t} className="flex items-center gap-2"><Check size={18} className="text-[#ffd54f]"/>{t}</span>)}</div></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-[2rem] bg-white p-7 text-[#113b2f] sm:col-span-2"><p className="text-xs font-black uppercase tracking-[.2em] text-[#147d64]">Oferta demonstrativa</p><h2 className="mt-4 text-4xl font-black">Ração Premium 15 kg</h2><p className="mt-3 text-slate-600">Preço e disponibilidade sujeitos à confirmação.</p><p className="mt-5 text-4xl font-black">R$ 159,90</p></div><div className="rounded-[2rem] bg-[#147d64] p-6"><Truck/><p className="mt-5 text-xl font-black">Entrega</p></div><div className="rounded-[2rem] bg-[#ffd54f] p-6 text-[#113b2f]"><Pill/><p className="mt-5 text-xl font-black">Farmácia pet</p></div></div></div></section>
<section id="catalogo" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="font-black uppercase tracking-[.2em] text-[#147d64]">Catálogo demonstrativo</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">Produtos para todos os pets.</h2><p className="mt-4 max-w-2xl text-lg text-slate-600">Itens e preços fictícios para apresentar o funcionamento do catálogo.</p></div><div className="relative"><Search className="absolute left-4 top-3.5 text-slate-400" size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} className="h-12 rounded-xl border border-green-100 bg-white pl-11 pr-4 lg:w-80" placeholder="Buscar produto"/></div></div><div className="mt-8 flex flex-wrap gap-2">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={`rounded-full px-4 py-2 text-sm font-black ${cat===c?"bg-[#113b2f] text-white":"bg-white text-slate-600"}`}>{c}</button>)}</div><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{filtered.map(p=>{const Icon=p.icon;return <article key={p.id} className="relative flex flex-col rounded-[1.75rem] border border-green-100 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl">{p.badge&&<span className="absolute right-4 top-4 rounded-full bg-[#ffd54f] px-3 py-1 text-[10px] font-black uppercase">{p.badge}</span>}<div className="grid h-24 place-items-center rounded-2xl bg-green-50 text-[#147d64]"><Icon size={46}/></div><p className="mt-5 text-xs font-black uppercase tracking-wider text-[#147d64]">{p.cat}</p><h3 className="mt-2 text-lg font-black">{p.name}</h3><p className="mt-2 text-sm text-slate-500">{p.detail}</p><div className="mt-auto pt-5">{p.old&&<p className="text-sm text-slate-400 line-through">{money(p.old)}</p>}<p className="text-2xl font-black">{money(p.price)}</p><button onClick={()=>order(p)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#25a866] px-4 py-3 font-black text-white">Consultar<MessageCircle size={17}/></button></div></article>})}</div></section>
<section id="beneficios" className="bg-[#eaf6ec] py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="font-black uppercase tracking-[.2em] text-[#147d64]">Facilidades</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">Mais conveniência para você e seu pet.</h2><div className="mt-14 grid gap-6 md:grid-cols-4">{benefits.map(([Icon,n,t])=><article key={n} className="rounded-[2rem] bg-white p-7"><div className="grid h-12 w-12 place-items-center rounded-xl bg-[#ffd54f]"><Icon/></div><h3 className="mt-6 text-xl font-black">{n}</h3><p className="mt-3 text-slate-600">{t}</p></article>)}</div></div></section>
<section id="farmacia" className="bg-[#113b2f] py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:px-8"><div><p className="font-black uppercase tracking-[.2em] text-[#ffd54f]">Farmácia pet</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">Cuidados importantes perto de casa.</h2><p className="mt-5 text-lg leading-8 text-green-100">Seção demonstrativa para destacar medicamentos, antipulgas, suplementos e produtos de higiene.</p><button onClick={()=>wa("Olá! Gostaria de informações sobre produtos da farmácia pet.")} className="mt-8 rounded-xl bg-[#ffd54f] px-6 py-4 font-black text-[#113b2f]">Consultar farmácia</button></div><div className="grid gap-5 sm:grid-cols-2">{products.filter(p=>p.cat==="Farmácia").map(p=>{const Icon=p.icon;return <article key={p.id} className="rounded-[2rem] border border-white/10 bg-white/5 p-7"><Icon className="text-[#ffd54f]"/><h3 className="mt-6 text-xl font-black">{p.name}</h3><p className="mt-3 text-green-100">{p.detail}</p><p className="mt-5 text-2xl font-black">{money(p.price)}</p></article>})}</div></div></section>
<section id="contato" className="py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="font-black uppercase tracking-[.2em] text-[#147d64]">Contato</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">Peça pelo WhatsApp.</h2><div className="mt-8 space-y-4 text-sm font-bold"><button onClick={()=>wa()} className="flex items-center gap-3"><MessageCircle className="text-[#25a866]" size={19}/>{B.waDisplay} (WhatsApp)</button><a href={B.phoneLink} className="flex items-center gap-3"><Phone className="text-[#147d64]" size={19}/>{B.phone} (telefone)</a><a href={B.maps} target="_blank" rel="noopener noreferrer" className="flex items-start gap-3"><MapPin className="mt-0.5 shrink-0 text-[#147d64]" size={19}/>{B.address}</a><p className="flex items-center gap-3"><Clock3 className="text-[#147d64]" size={19}/>Seg. a sex. 09:00–21:00; sáb. 09:00–20:00; dom. 09:00–17:00.</p></div></div><form onSubmit={submit} className="grid gap-5 rounded-[2rem] bg-white p-8 shadow-xl sm:grid-cols-2"><div className="sm:col-span-2"><label className="mb-2 block text-sm font-black">Nome</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="h-12 w-full rounded-xl border border-green-100 px-4"/></div><div className="sm:col-span-2"><label className="mb-2 block text-sm font-black">Telefone</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="h-12 w-full rounded-xl border border-green-100 px-4"/></div><div><label className="mb-2 block text-sm font-black">Pet</label><div className="relative"><select value={form.pet} onChange={e=>setForm({...form,pet:e.target.value})} className="h-12 w-full appearance-none rounded-xl border border-green-100 bg-white px-4"><option>Cachorro</option><option>Gato</option><option>Outro</option></select><ChevronDown className="pointer-events-none absolute right-3 top-3 text-slate-400"/></div></div><div><label className="mb-2 block text-sm font-black">Interesse</label><div className="relative"><select value={form.need} onChange={e=>setForm({...form,need:e.target.value})} className="h-12 w-full appearance-none rounded-xl border border-green-100 bg-white px-4"><option>Comprar produtos</option><option>Farmácia pet</option><option>Entrega</option><option>Leva e traz</option><option>Outro</option></select><ChevronDown className="pointer-events-none absolute right-3 top-3 text-slate-400"/></div></div><div className="sm:col-span-2"><label className="mb-2 block text-sm font-black">Mensagem</label><textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value})} rows="4" className="w-full rounded-xl border border-green-100 p-4"/></div><button disabled={!valid} className="flex items-center justify-center gap-2 rounded-xl bg-[#113b2f] px-6 py-4 font-black text-white disabled:opacity-40 sm:col-span-2">Conversar pelo WhatsApp<MessageCircle size={19}/></button></form></div></section>
<footer className="bg-[#0b2a21] py-8 text-green-100"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 px-5 text-sm sm:flex-row lg:px-8"><p>© 2026 Mercadão Pet Capão Redondo.</p><p>Projeto demonstrativo independente. Produtos, preços, horários e serviços sujeitos à confirmação.</p></div></footer><button onClick={()=>wa()} className="fixed bottom-5 right-5 z-40 flex h-14 items-center gap-2 rounded-full bg-[#25a866] px-5 font-black text-white shadow-xl"><MessageCircle size={22}/><span className="hidden sm:inline">WhatsApp</span></button></main>}
export default App;
